### ISSUE TITLE
pip - ERROR: No matching distribution found for git-story

### ISSUE THREAD

**Issue by LoganTann** [initialcommit-com/git-story#1]
Hello, I tried to install using pip, but it shows this error : 

```diff
- ERROR: Could not find a version that satisfies the requirement git-story (from versions: none)
- ERROR: No matching distribution found for git-story
```

Command history :  

```sh
sudo apt install libcairo2-dev libpango1.0-dev ffmpeg python3-pip
pip3 install manim
pip3 install gitpython
pip3 install git-story
```

I'm using ubuntu 20.04 with wsl (5.10.102.1-microsoft-standard-WSL2)

**Comment by salman0ansari** [comment]
python and pip version?

**Comment by LoganTann** [comment]
python 3.8.10 / pip 20.0.2

**Comment by initialcommit-io** [comment]
Oh, it might be beceause minimum supported Python version in my setup.py is `python_requires='>=3.9'` and you're on 3.8.x.

I just updated the minimum required Python version to 3.7.x, so it might work now.  Can you try again and let me know?

**Comment by LoganTann** [comment]
Works as expected, thanks !
