### ISSUE TITLE
Error installing using pip

### ISSUE THREAD

**Issue by salman0ansari** [initialcommit-com/git-story#2]
Error Log
```
Collecting click>=7.2
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
  creating build/temp.linux-x86_64-cpython-39
  creating build/temp.linux-x86_64-cpython-39/cairo
  copying manimpango/cmanimpango.pyx -> build/lib.linux-x86_64-cpython-39/manimpango
  running build_ext
  building 'manimpango.cmanimpango' extension
  creating build/temp.linux-x86_64-cpython-39
  creating build/temp.linux-x86_64-cpython-39/manimpango
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/python3.9 -c manimpango/cmanimpango.c -o build/temp.linux-x86_64-cpython-39/manimpango/cmanimpango.o
  manimpango/cmanimpango.c:44:10: fatal error: Python.h: No such file or directory

44 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
    ERROR: Failed building wheel for pycairo
Failed to build manimpango pycairo
ERROR: Could not build wheels for manimpango, pycairo, which is required to install pyproject.toml-based projects

```
Commands Used
- sudo apt install libcairo2-dev libpango1.0-dev ffmpeg python3-pip
- pip3 install manim
- pip3 install gitpython
- pip3 install git-story `Error on this cmd`

**Comment by initialcommit-io** [comment]
Can you let me know the OS version and Python version you're using?

**Comment by salman0ansari** [comment]
OS: `Ubuntu 20.04`
Python Version: `3.9.13`

**Comment by initialcommit-io** [comment]
Can you try this and let me know if it works after?

`sudo apt install python3.9-dev`

If that doesn't work, can you send me the output of running `pip3 list`

**Comment by salman0ansari** [comment]
> Can you try this and let me know if it works after?
> 
> `sudo apt install python3.9-dev`
> 
> If that doesn't work, can you send me the output of running `pip3 list`


After running this cmd `sudo apt install python3.9-dev`  
I tried installing again and got this error
```
Collecting manimpango<0.5.0,>=0.4.0.post0
  Using cached ManimPango-0.4.1.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Package pangocairo was not found in the pkg-config search path.
      Perhaps you should add the directory containing `pangocairo.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'pangocairo' found
      Traceback (most recent call last):
        File "<string>", line 136, in check_min_version
        File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/ubuntu/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/ubuntu/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ubuntu/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-4a79pkwb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-4a79pkwb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-4a79pkwb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-4a79pkwb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 203, in <module>
        File "<string>", line 139, in check_min_version
      __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by salman0ansari** [comment]
```
$ pip3 list
```

```
Package Version
------- -------
pip     22.1.2
```

**Comment by salman0ansari** [comment]
> > Can you try this and let me know if it works after?
> > `sudo apt install python3.9-dev`
> > If that doesn't work, can you send me the output of running `pip3 list`
> 
> After running this cmd `sudo apt install python3.9-dev` I tried installing again and got this error
> 
> ```
> Collecting manimpango<0.5.0,>=0.4.0.post0
>   Using cached ManimPango-0.4.1.tar.gz (4.1 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [30 lines of output]
>       Package pangocairo was not found in the pkg-config search path.
>       Perhaps you should add the directory containing `pangocairo.pc'
>       to the PKG_CONFIG_PATH environment variable
>       No package 'pangocairo' found
>       Traceback (most recent call last):
>         File "<string>", line 136, in check_min_version
>         File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
>           raise CalledProcessError(retcode, cmd)
>       subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.
>       
>       During handling of the above exception, another exception occurred:
>       
>       Traceback (most recent call last):
>         File "/home/ubuntu/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
>           main()
>         File "/home/ubuntu/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/home/ubuntu/.local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "/tmp/pip-build-env-4a79pkwb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
>           return self._get_build_requires(
>         File "/tmp/pip-build-env-4a79pkwb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
>           self.run_setup()
>         File "/tmp/pip-build-env-4a79pkwb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
>           super(_BuildMetaLegacyBackend,
>         File "/tmp/pip-build-env-4a79pkwb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
>           exec(code, locals())
>         File "<string>", line 203, in <module>
>         File "<string>", line 139, in check_min_version
>       __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```
Solved after running this cmd:
https://github.com/ManimCommunity/ManimPango/issues/53#issuecomment-901546167

**Comment by initialcommit-io** [comment]
Oh that's great - so It's working for you now?

**Comment by salman0ansari** [comment]
Yes working good
