### ISSUE TITLE
problem in running git-story

### ISSUE THREAD

**Issue by binayakbishnu** [initialcommit-com/git-story#3]
'git-story' is not recognized as an internal or external command,
operable program or batch file.

Installation has been correct
![image](https://user-images.githubusercontent.com/71837066/179802521-4e0db916-316a-4f87-844e-a426e9b512a5.png)

**Comment by initialcommit-io** [comment]
Looks like you're on Windows. Can you let me know the version of Windows and the installation steps you used?

I'm wondering if maybe it got installed but not added to the PATH.  Also, did you try closing and reopening the CMD Terminal after installation?

**Comment by binayakbishnu** [comment]
1. Windows 11
2. I followed the steps mentioned: manim -> gitpython -> git-story
3. What all do I need to add to PATH?
4. Yep reopened CMD

**Comment by initialcommit-io** [comment]
Did you install on Windows subsystem for Linux?  Or just regular Windows?

If on regular Windows, can you try locating the following folder and check to see if the "git-story" executable is in there?

`C:\PythonXX\Scripts`

It might not be in that exact location, but apparently, there should be a "Scripts" folder within your Python installation that is where the executables get put by default.

**Comment by binayakbishnu** [comment]
Nope based on the above screenshot my packages get installed in C:\Users\\......\AppData\Roaming\Python\Python310\site-packages

Do I have to somehow install git-story globally for it to work?

**Comment by initialcommit-io** [comment]
The `site-packages` folder contains the Python module, but the install process should also have created an executable file somewhere called `git-story`.  That's what I was trying to ask about.  Can you search your PC for a file called "git-story"?  On Windows it is probably "git-story.exe".

I'm guessing it was created somewhere that is not on your `PATH` environment variable, so if we locate the directory it's in you can try adding it to your PATH environment variable.

**Comment by binayakbishnu** [comment]
Couldn't find it anywhere apart from site-packages although I installed it.
There is a git_story.py but no git-story.exe.

![image](https://user-images.githubusercontent.com/71837066/180486179-468dba7b-1208-4721-ad09-83079f35120b.png)

**Comment by initialcommit-io** [comment]
That's weird if the install was successful it should have created the executable somewhere.  From some StackOverflow posts (https://stackoverflow.com/questions/46486236/python-execute-console-script-on-windows) it looks like it should be in a folder called "Scripts" within your Python home folder.  Can you see if it exists in the these locations:

C:\Users\bishn\AppData\Roaming\Python\Scripts
or
C:\Users\bishn\AppData\Roaming\Python\Python310\Scripts

**Comment by initialcommit-io** [comment]
Actually, I think I found some threads that will help you, please check these out and let me know if you're able to resolve:

https://discuss.python.org/t/windows-appdata-roaming-vs-local/2682

https://github.com/pypa/pip/issues/7209

**Comment by initialcommit-io** [comment]
Did you get a chance to check these threads?

**Comment by binayakbishnu** [comment]
I found git-story.exe
Now I just have to add the folder to PATH and run normally via project directory?

**Comment by initialcommit-io** [comment]
Oh ok that's great - can you let me know the full path to the folder you found `git-story.exe` in?  It might help someone in the future.

And yes, that's correct! Just make sure to close and repoen your terminal after making the environment variable change for it to take effect.

**Comment by binayakbishnu** [comment]
Thank you @initialcommit-io 
Here's the PATH I found it on: ```C:\Users\......\AppData\Roaming\Python\Python310\Scripts```
