### ISSUE TITLE
Question: Speed

### ISSUE THREAD

**Issue by bdmorin** [initialcommit-com/git-story#4]
Any plans to implement a speed option to speed up the animation?

**Comment by initialcommit-io** [comment]
There is a `--low-quality` option that speeds it up by rendering in lower quality - did you try that?  But due to Manim library it still takes time to render video.

**Comment by bdmorin** [comment]
My bad, I wasn't clear - I meant playback speed. I was wondering if there was a way to have the final animation literally play faster, without fiddling with a player.

Does that make more sense? (sorry, getting over Covid)

**Comment by initialcommit-io** [comment]
Hi there, I pushed a new feature for this.  You can now use the `--speed` command line option to change the animation speed.

Example to run twice as fast:
$ git-story --speed=2

Example to run half as fast:
$ git-story --speed=0.5

You'll need to update the git-story package using:  `pip3 install git-story -U`
And make sure you see that the updated version 0.1.4 is installed after running that (if not, run it again).

**Comment by bdmorin** [comment]
I'll check this out, thank you!

**Comment by initialcommit-io** [comment]
Were you able to test this?

**Comment by initialcommit-io** [comment]
Just checking in - were you able to test this out?

**Comment by initialcommit-io** [comment]
Closing since feature was implemented.
