### ISSUE TITLE
Requires system dependencies libsdl-pango-dev

### ISSUE THREAD

**Issue by bagerard** [initialcommit-com/git-story#5]
First of all, I just heard about this package and it's pretty cool, thanks!

Next, I noticed that I was missing some system dependencies to be able to pip install git-story

It was failing with the following

```
      subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/bgerard/.pyenv/versions/3.9.7/envs/flake8-illegal-import/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        [...]
        File "<string>", line 139, in check_min_version
      __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

And I had to install the following system packages:
```
sudo apt-get install libsdl-pango-dev
```

Shall I add this to the Readme?

**Comment by initialcommit-io** [comment]
Hi there!  Thanks a lot for trying out git-story and reporting this even though you were able to resolve it.  The thing is most users didn't run into this issue, so I think it must only happen in specific scenarios.  If we add something to the readme it needs to cover only the specific situation where it's needed.

Can you provide your OS and version, Python version, and installation steps?

**Comment by bagerard** [comment]
I m on Ubuntu 20.04 (LTS), I ve tried with different version of Python (3.8 and 3.9) but it didn't matter as it was missing the system package. Up to you if you want to add it or not
